export default {
  name: 'wisata',
  title: 'Kegiatan Wisata',
  type: 'document',
  fields: [
    {
      name: 'nama',
      title: 'Nama Kegiatan Wisata',
      type: 'string',
      description: 'Contoh: Jejak Laut Kabola, Jejak Warisan Kabola, dll.',
      validation: (Rule: any) => Rule.required(),
    },
    {
      name: 'slug',
      title: 'Slug (URL)',
      type: 'slug',
      description: 'Dibuat otomatis dari Nama Kegiatan Wisata. Klik "Generate". Digunakan sebagai URL halaman detail.',
      options: {
        source: 'nama',
        maxLength: 96,
      },
      validation: (Rule: any) => Rule.required(),
    },
    {
      name: 'deskripsi',
      title: 'Deskripsi Singkat',
      type: 'text',
      rows: 3,
      description: 'Ringkasan cerita tentang kegiatan wisata ini. Tampil di kartu katalog.',
    },
    {
      name: 'overview',
      title: 'Overview & Narasi Lengkap Kegiatan',
      type: 'text',
      rows: 8,
      description: 'Naskah narasi lengkap cerita pengalaman kegiatan wisata. Tampil di halaman detail.',
    },
    {
      name: 'highlights',
      title: 'Highlight Pengalaman (Poin Kunci)',
      type: 'array',
      description: 'Poin-poin pengalaman menarik yang didapat wisatawan.',
      of: [{ type: 'string' }],
    },
    {
      name: 'hargaTiket',
      title: 'Harga / Biaya Paket',
      type: 'string',
      description: 'Contoh: Hubungi Pengelola, Rp 150.000/orang, dll.',
    },
    {
      name: 'durasiWisata',
      title: 'Estimasi Durasi Kunjungan',
      type: 'string',
      description: 'Label durasi yang tampil di badge kartu. Contoh: Setengah Hari, Seharian, 2–3 Jam.',
    },
    {
      name: 'namaPengelola',
      title: 'Nama Pengelola / Kontak',
      type: 'string',
      description: 'Contoh: Pak One, Pak Moses, Pokdarwis Kabola.',
    },
    {
      name: 'kontakWa',
      title: 'Nomor WhatsApp Reservasi',
      type: 'string',
      description: 'Format: 628xxxxxxxxx (awali dengan 62). Contoh: 6281236978212 (Pak One) atau 6281338619737 (Pak Moses).',
    },
    {
      name: 'foto',
      title: 'Foto / Poster Utama',
      type: 'image',
      description: 'Foto poster kegiatan wisata. Tampil sebagai gambar utama di kartu dan halaman detail.',
      options: {
        hotspot: true,
      },
    },
    {
      name: 'galeri',
      title: 'Galeri Foto Tambahan',
      type: 'array',
      description: 'Foto-foto tambahan yang tampil di bagian galeri halaman detail.',
      of: [{ type: 'image', options: { hotspot: true } }],
    },
    {
      name: 'fasilitas',
      title: 'Fasilitas / Inklusi Tersedia',
      type: 'array',
      description: 'Daftar fasilitas/inklusi yang ada (contoh: Perahu, Pemandu Lokal, Alat Snorkeling).',
      of: [{ type: 'string' }],
      options: {
        layout: 'tags',
      },
    },
    {
      name: 'lokasiMaps',
      title: 'Link Google Maps Spot Kunjungan',
      type: 'url',
      description: 'Salin link berbagi dari Google Maps.',
    },
  ],
}
